FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

WORKDIR /app

# Copiar apenas arquivos de configuração para cache de camadas
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/typescript-config/package.json ./packages/typescript-config/
COPY apps/omni-gateway/package.json ./apps/omni-gateway/

# Instalar dependências
ENV NODE_ENV=development
RUN pnpm install --frozen-lockfile --shamefully-hoist

# O código será montado via volume

WORKDIR /app/apps/omni-gateway

CMD ["pnpm", "dev"]
